// Code generated by MockGen. DO NOT EDIT.
// Source: formatter.go

// Package mock_formatter is a generated GoMock package.
package mock_formatter

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	metrics "github.com/kdimtriCP/gh-inspector/internal/metrics"
)

// MockFormatter is a mock of Formatter interface.
type MockFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockFormatterMockRecorder
}

// MockFormatterMockRecorder is the mock recorder for MockFormatter.
type MockFormatterMockRecorder struct {
	mock *MockFormatter
}

// NewMockFormatter creates a new mock instance.
func NewMockFormatter(ctrl *gomock.Controller) *MockFormatter {
	mock := &MockFormatter{ctrl: ctrl}
	mock.recorder = &MockFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormatter) EXPECT() *MockFormatterMockRecorder {
	return m.recorder
}

// Format mocks base method.
func (m *MockFormatter) Format(writer io.Writer, metrics []*metrics.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Format", writer, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// Format indicates an expected call of Format.
func (mr *MockFormatterMockRecorder) Format(writer, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Format", reflect.TypeOf((*MockFormatter)(nil).Format), writer, metrics)
}
