github_token: "ghp_yourtokenhere"
output_format: "table"
cache:
  enabled: true
  ttl: 3600  # 1 hour
  directory: ""  # empty means use default .gh-inspector-cache in current directory

scoring:
  weights:
    stars: 0.20
    forks: 0.08
    recent_activity: 0.18
    open_issues: 0.08
    open_prs: 0.04
    has_license: 0.04
    has_cicd: 0.04
    has_contributing: 0.04
    release_frequency: 0.12
    has_readme: 0.03
    has_code_of_conduct: 0.03
    has_security: 0.03
    watchers: 0.09
